# Generated by Django 2.1.1 on 2018-09-02 04:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('microfone', '0002_auto_20180901_1813'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vozusuario',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='vozusuario',
            name='object_id',
        ),
    ]
