# Generated by Django 2.1.1 on 2018-09-01 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImagemUsuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagemusuario_padrao', models.ImageField(height_field='imagemusuario_padrao_height', upload_to='', width_field='imagemusuario_padrao_width')),
                ('imagemusuario_padrao_width', models.IntegerField(default=0)),
                ('imagemusuario_padrao_height', models.IntegerField(default=0)),
            ],
        ),
    ]
