# Generated by Django 2.1.1 on 2018-09-02 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camera', '0003_auto_20180902_0446'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagemusuario',
            name='imagemusuario_padrao_height',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='imagemusuario',
            name='imagemusuario_padrao_width',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
